# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
version: 2
jobs:
  deploy:
    docker:
      # specify the version you desire here
      # - image: circleci/ruby:2.7.0
      - image: smellman/phaarmacies-tiles:1.0.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # - run:
      #     name: install dependencies
      #     command: |
      #       git clone https://github.com/mapbox/tippecanoe.git
      #       cd tippecanoe
      #       make -j
      #       sudo make install
      #       rm -rf tippecanoe

      - add_ssh_keys:
          fingerprints:
            - "f0:18:cd:40:47:e1:f0:85:d0:f2:6b:39:66:d7:d1:40"
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git config --global user.email hal@code4japan.org
                git config --global user.name circleci
                git checkout gh-pages
                git filter-branch -f --index-filter 'git rm -r --ignore-unmatch zxy' --prune-empty -- --all
                git filter-branch -f --index-filter 'git rm --ignore-unmatch pharmacies.mbtiles' --prune-empty -- --all
                rm -rf .git/refs/original/
                git reflog expire --expire=now --all
                git gc --aggressive --prune=now
                git checkout master index.html
                rake; git add .; git commit -m "From `git log --oneline origin/master -n 1`"; git push -f
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
  cronjob:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *" #every 5 minutes
          filters:
            branches:
              only: master
    jobs:
      - deploy
